backend = "wal"
color_space = "lab"
palette = "dark16"
check_contrast = true

[templates]
xres.src = "xresources.template"
xres.dst = "~/.cache/wallust/colors.Xresources"

dunst.src = "dunstrc.template"
dunst.dst = "~/.config/dunst/dunstrc"

sequences.src = "sequences.template"
sequences.dst = "~/.cache/wallust/sequences"